name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Validate Maven Wrapper
        run: mvn --version

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run Tests with Coverage
        run: mvn test jacoco:report

      - name: Archive Coverage Data
        uses: actions/upload-artifact@v3
        with:
          name: maven-coverage-data-jacoco
          path: target/site/jacoco

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.3.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: ". /data/results"

      - name: Download Coverage Data
        uses: actions/download-artifact@v3
        with:
          name: maven-coverage-data-jacoco
          path: qodana/results/jacoco

      - name: Run Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: ". /data/results"
